# Generated by Django 4.2.1 on 2023-06-27 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyectodjango', '0003_rename_usuario_usuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='contrasenia',
            field=models.CharField(max_length=100),
        ),
    ]
