# Generated by Django 4.2.1 on 2023-06-27 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyectodjango', '0004_alter_usuarios_contrasenia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='numFono',
            field=models.CharField(max_length=100),
        ),
    ]
